### ISSUE TITLE
Django server: Port 8000 already in use

### ISSUE THREAD

**Issue by sebastian-philipp** [ricardoasmarques/vagrant-openattic-docker#11]
Hi Ricardo,

I'm getting this:
```
ssh://vagrant@192.168.121.6:22/home/vagrant/env/bin/python -u /home/vagrant/openattic/backend/manage.py runserver 0.0.0.0:8000
..snip...
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Error: That port is already in use.

Process finished with exit code 1
```

Turns out, `salt-api` already uses port 8000. 

What do you think of changing the salt-api port to something different? My workaround is of course changing the Django server's port.

**Comment by ricardoasmarques** [comment]
Thank you for your feedback @sebastian-philipp.

The salt-api is installed by DeepSea, and DeepSea configures the salt-api to run on port 8000 (see [salt-api.conf.j2](https://github.com/SUSE/DeepSea/blob/c646ed43b8b10f3dcce56f66c84d20281fea6559/srv/salt/ceph/salt-api/files/salt-api.conf.j2)).

As it is currently not possible to set this value in DeepSea (unless we use some hack),  I will suggest that, for now,  we should run openATTIC on a different port like described on [README](https://github.com/ricardoasmarques/vagrant-openattic-docker/blob/master/README.md).
